### ISSUE TITLE
Automatic Raw input Saving during User experience to prevent large data loss from crashes

### ISSUE THREAD

**Issue by Flovdl** [kobebryant432/PyPadel#27]

**Comment by TomMoeras** [comment]
I added this within our current structure for inputting (see pull request #28). I think eventually we want to move away from keeping input and database seperate. Perhaps it would be better to immediately add the match data to the database and keep updating it live and also read it from there (currently the user inputs the whole match and it is manually added to a database afterwards). I think this would also make it easier to allow inputs on a web interface instead of the terminal.
